### ISSUE TITLE
Don't Include Class Files

### ISSUE THREAD

**Issue by TimBednarzyk** [btmangan/Javamon#3]
You shouldn't put *.class files in a Github repository. If you want to be sure that they won't show up, consider using a gitignore file and excluding *.class files.

**Comment by btmangan** [comment]
Very useful functionality. I was worrying about those compiled files muddying up the repo. 

Updated and recompiled. "Git Status" shows full sync with compiled files in directory. 

Always appreciate a nudge in the right direction.
